apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
 # namespace: default
  #labels:
  #  kueue.x-k8s.io/queue-name: dws-local-queue
  annotations:
      cluster-autoscaler.kubernetes.io/consume-provisioning-request: dws-prov-request
      cluster-autoscaler.kubernetes.io/provisioning-class-name: "queued-provisioning.gke.io"
spec:
  #parallelism: 1
  #completions: 1
  #suspend: true
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: NODE-POOL-NAME
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "cloud.google.com/gke-queued"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["120s"]
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
            nvidia.com/gpu: 2
          limits:
            cpu: "100m"
            memory: "100Mi"
            nvidia.com/gpu: 2
      restartPolicy: Never
