apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-fine-tune
  namespace: kubeflow
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
           nodeSelector:
             cloud.google.com/gke-accelerator: nvidia-l4
           containers:
            - name: pytorch
              image: us-east1-docker.pkg.dev/rick-vertex-ai/gke-llm/kubeflow-finetune:latest
              imagePullPolicy: Always
              env:
                - name: model_uri
                  value: hf://TinyLlama/TinyLlama-1.1B-Chat-v1.0
                - name: dataset_repo
                  value: imdatta0/ultrachat_1k
              command:
                - "python3"
                - "/app/fine-tune.py"
              resources:
                limits:
                  nvidia.com/gpu: 1
             
             
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          nodeSelector:
             cloud.google.com/gke-accelerator: nvidia-l4
          containers:
            - name: pytorch
              image: us-east1-docker.pkg.dev/rick-vertex-ai/gke-llm/kubeflow-finetune:latest
              imagePullPolicy: Always
              command:
                - "python3"
                - "/app/fine-tune.py"
              resources:
                limits:
                  nvidia.com/gpu: 1
            